```yaml
version: '3.8'
services:
  backend:
    image: <dockerhub-username>/blogdemo-backend:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://blogdemo.123456789012.us-east-1.rds.amazonaws.com:5432/blogdemo
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    networks:
      - blogdemo-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    deploy:
      replicas: 1
    networks:
      - blogdemo-network
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - blogdemo-network
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - blogdemo-network
  node-exporter:
    image: prom/node-exporter:latest
    networks:
      - blogdemo-network
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - blogdemo-network
secrets:
  db_password:
    external: true
networks:
  blogdemo-network:
    driver: overlay
```
